cmake_minimum_required(VERSION 3.20)

project(Cpp-Workspace CXX)

# Enforce modern standards
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_subdirectory(Cpp001_helloworld)
# add_subdirectory()
# add_subdirectory()
add_subdirectory(Cpp004_references)
add_subdirectory(Cpp005_classes)
add_subdirectory(Cpp006_static)
add_subdirectory(Cpp007_enums)
add_subdirectory(Cpp009_inheritance)
add_subdirectory(Cpp010_virtual_functions)
add_subdirectory(Cpp011_interfaces)
add_subdirectory(Cpp012_visibility)
add_subdirectory(Cpp013_separate_compilation)
add_subdirectory(Cpp014_namespace)
add_subdirectory(Cpp015_error_handling)
add_subdirectory(Cpp016_member_initializer_list)
add_subdirectory(Cpp017_const_and_mutable)
add_subdirectory(Cpp018_object_instantiation)
add_subdirectory(Cpp019_new_and_delete)
add_subdirectory(Cpp020_this_keyword)

add_subdirectory(Mini-Projects/MP001_ring_buffer)
add_subdirectory(Mini-Projects/MP002_datalogger)
