// Specify the syntax version

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: sysmanager.proto

// Create a namespace for generated C++ classes

package sysmanager

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SystemManager_GetSystemStatus_FullMethodName         = "/sysmanager.SystemManager/GetSystemStatus"
	SystemManager_TriggerEnclosureControl_FullMethodName = "/sysmanager.SystemManager/TriggerEnclosureControl"
	SystemManager_StreamWeatherTelemetry_FullMethodName  = "/sysmanager.SystemManager/StreamWeatherTelemetry"
	SystemManager_UploadFirmware_FullMethodName          = "/sysmanager.SystemManager/UploadFirmware"
	SystemManager_ActiveMotorControl_FullMethodName      = "/sysmanager.SystemManager/ActiveMotorControl"
)

// SystemManagerClient is the client API for SystemManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Define the Actions (Service)
type SystemManagerClient interface {
	// UNARY RPCs: One request, one response.
	GetSystemStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	TriggerEnclosureControl(ctx context.Context, in *EnclosureControlRequest, opts ...grpc.CallOption) (*EnclosureControlResponse, error)
	// SERVER STREAMING: Returns a stream of data
	StreamWeatherTelemetry(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WeatherTelemetry], error)
	// CLIENT STREAMING: Accepts a stream of Data
	UploadFirmware(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FirmwareChunk, UploadResult], error)
	// BIDIRECTIONAL STREAMING: Both sides stream
	ActiveMotorControl(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MotorCommand, MotorTelemetry], error)
}

type systemManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemManagerClient(cc grpc.ClientConnInterface) SystemManagerClient {
	return &systemManagerClient{cc}
}

func (c *systemManagerClient) GetSystemStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, SystemManager_GetSystemStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemManagerClient) TriggerEnclosureControl(ctx context.Context, in *EnclosureControlRequest, opts ...grpc.CallOption) (*EnclosureControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnclosureControlResponse)
	err := c.cc.Invoke(ctx, SystemManager_TriggerEnclosureControl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemManagerClient) StreamWeatherTelemetry(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WeatherTelemetry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemManager_ServiceDesc.Streams[0], SystemManager_StreamWeatherTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WeatherRequest, WeatherTelemetry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemManager_StreamWeatherTelemetryClient = grpc.ServerStreamingClient[WeatherTelemetry]

func (c *systemManagerClient) UploadFirmware(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FirmwareChunk, UploadResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemManager_ServiceDesc.Streams[1], SystemManager_UploadFirmware_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FirmwareChunk, UploadResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemManager_UploadFirmwareClient = grpc.ClientStreamingClient[FirmwareChunk, UploadResult]

func (c *systemManagerClient) ActiveMotorControl(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MotorCommand, MotorTelemetry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemManager_ServiceDesc.Streams[2], SystemManager_ActiveMotorControl_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MotorCommand, MotorTelemetry]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemManager_ActiveMotorControlClient = grpc.BidiStreamingClient[MotorCommand, MotorTelemetry]

// SystemManagerServer is the server API for SystemManager service.
// All implementations must embed UnimplementedSystemManagerServer
// for forward compatibility.
//
// Define the Actions (Service)
type SystemManagerServer interface {
	// UNARY RPCs: One request, one response.
	GetSystemStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	TriggerEnclosureControl(context.Context, *EnclosureControlRequest) (*EnclosureControlResponse, error)
	// SERVER STREAMING: Returns a stream of data
	StreamWeatherTelemetry(*WeatherRequest, grpc.ServerStreamingServer[WeatherTelemetry]) error
	// CLIENT STREAMING: Accepts a stream of Data
	UploadFirmware(grpc.ClientStreamingServer[FirmwareChunk, UploadResult]) error
	// BIDIRECTIONAL STREAMING: Both sides stream
	ActiveMotorControl(grpc.BidiStreamingServer[MotorCommand, MotorTelemetry]) error
	mustEmbedUnimplementedSystemManagerServer()
}

// UnimplementedSystemManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemManagerServer struct{}

func (UnimplementedSystemManagerServer) GetSystemStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemStatus not implemented")
}
func (UnimplementedSystemManagerServer) TriggerEnclosureControl(context.Context, *EnclosureControlRequest) (*EnclosureControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerEnclosureControl not implemented")
}
func (UnimplementedSystemManagerServer) StreamWeatherTelemetry(*WeatherRequest, grpc.ServerStreamingServer[WeatherTelemetry]) error {
	return status.Error(codes.Unimplemented, "method StreamWeatherTelemetry not implemented")
}
func (UnimplementedSystemManagerServer) UploadFirmware(grpc.ClientStreamingServer[FirmwareChunk, UploadResult]) error {
	return status.Error(codes.Unimplemented, "method UploadFirmware not implemented")
}
func (UnimplementedSystemManagerServer) ActiveMotorControl(grpc.BidiStreamingServer[MotorCommand, MotorTelemetry]) error {
	return status.Error(codes.Unimplemented, "method ActiveMotorControl not implemented")
}
func (UnimplementedSystemManagerServer) mustEmbedUnimplementedSystemManagerServer() {}
func (UnimplementedSystemManagerServer) testEmbeddedByValue()                       {}

// UnsafeSystemManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemManagerServer will
// result in compilation errors.
type UnsafeSystemManagerServer interface {
	mustEmbedUnimplementedSystemManagerServer()
}

func RegisterSystemManagerServer(s grpc.ServiceRegistrar, srv SystemManagerServer) {
	// If the following call panics, it indicates UnimplementedSystemManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemManager_ServiceDesc, srv)
}

func _SystemManager_GetSystemStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemManagerServer).GetSystemStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemManager_GetSystemStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemManagerServer).GetSystemStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemManager_TriggerEnclosureControl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnclosureControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemManagerServer).TriggerEnclosureControl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemManager_TriggerEnclosureControl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemManagerServer).TriggerEnclosureControl(ctx, req.(*EnclosureControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemManager_StreamWeatherTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WeatherRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemManagerServer).StreamWeatherTelemetry(m, &grpc.GenericServerStream[WeatherRequest, WeatherTelemetry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemManager_StreamWeatherTelemetryServer = grpc.ServerStreamingServer[WeatherTelemetry]

func _SystemManager_UploadFirmware_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SystemManagerServer).UploadFirmware(&grpc.GenericServerStream[FirmwareChunk, UploadResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemManager_UploadFirmwareServer = grpc.ClientStreamingServer[FirmwareChunk, UploadResult]

func _SystemManager_ActiveMotorControl_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SystemManagerServer).ActiveMotorControl(&grpc.GenericServerStream[MotorCommand, MotorTelemetry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemManager_ActiveMotorControlServer = grpc.BidiStreamingServer[MotorCommand, MotorTelemetry]

// SystemManager_ServiceDesc is the grpc.ServiceDesc for SystemManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sysmanager.SystemManager",
	HandlerType: (*SystemManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemStatus",
			Handler:    _SystemManager_GetSystemStatus_Handler,
		},
		{
			MethodName: "TriggerEnclosureControl",
			Handler:    _SystemManager_TriggerEnclosureControl_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamWeatherTelemetry",
			Handler:       _SystemManager_StreamWeatherTelemetry_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadFirmware",
			Handler:       _SystemManager_UploadFirmware_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ActiveMotorControl",
			Handler:       _SystemManager_ActiveMotorControl_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sysmanager.proto",
}
