// Specify the syntax version

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sysmanager.proto

// Create a namespace for generated C++ classes

package sysmanager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ================================================
// ENUMS
// ================================================
type SystemState int32

const (
	SystemState_SYSTEM_STATE_UNSPECIFIED SystemState = 0
	SystemState_SYSTEM_STATE_BOOTING     SystemState = 1
	SystemState_SYSTEM_STATE_IDLE        SystemState = 2
	SystemState_SYSTEM_STATE_ACTIVE      SystemState = 3
	SystemState_SYSTEM_STATE_FAULT       SystemState = 4
)

// Enum value maps for SystemState.
var (
	SystemState_name = map[int32]string{
		0: "SYSTEM_STATE_UNSPECIFIED",
		1: "SYSTEM_STATE_BOOTING",
		2: "SYSTEM_STATE_IDLE",
		3: "SYSTEM_STATE_ACTIVE",
		4: "SYSTEM_STATE_FAULT",
	}
	SystemState_value = map[string]int32{
		"SYSTEM_STATE_UNSPECIFIED": 0,
		"SYSTEM_STATE_BOOTING":     1,
		"SYSTEM_STATE_IDLE":        2,
		"SYSTEM_STATE_ACTIVE":      3,
		"SYSTEM_STATE_FAULT":       4,
	}
)

func (x SystemState) Enum() *SystemState {
	p := new(SystemState)
	*p = x
	return p
}

func (x SystemState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemState) Descriptor() protoreflect.EnumDescriptor {
	return file_sysmanager_proto_enumTypes[0].Descriptor()
}

func (SystemState) Type() protoreflect.EnumType {
	return &file_sysmanager_proto_enumTypes[0]
}

func (x SystemState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemState.Descriptor instead.
func (SystemState) EnumDescriptor() ([]byte, []int) {
	return file_sysmanager_proto_rawDescGZIP(), []int{0}
}

// ================================================
// EXAMPLE 01 : UNARY MESSAGES
// ================================================
// 1. Define the Data Structures (Messages)
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentName string                 `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_sysmanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sysmanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_sysmanager_proto_rawDescGZIP(), []int{0}
}

func (x *StatusRequest) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOnline      bool                   `protobuf:"varint,1,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	CurrentState  string                 `protobuf:"bytes,2,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_sysmanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sysmanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_sysmanager_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *StatusResponse) GetCurrentState() string {
	if x != nil {
		return x.CurrentState
	}
	return ""
}

type EnclosureControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        int32                  `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"` // e.g. 1 = Open, 2 = Close
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnclosureControlRequest) Reset() {
	*x = EnclosureControlRequest{}
	mi := &file_sysmanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnclosureControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnclosureControlRequest) ProtoMessage() {}

func (x *EnclosureControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sysmanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnclosureControlRequest.ProtoReflect.Descriptor instead.
func (*EnclosureControlRequest) Descriptor() ([]byte, []int) {
	return file_sysmanager_proto_rawDescGZIP(), []int{2}
}

func (x *EnclosureControlRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

type EnclosureControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnclosureControlResponse) Reset() {
	*x = EnclosureControlResponse{}
	mi := &file_sysmanager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnclosureControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnclosureControlResponse) ProtoMessage() {}

func (x *EnclosureControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sysmanager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnclosureControlResponse.ProtoReflect.Descriptor instead.
func (*EnclosureControlResponse) Descriptor() ([]byte, []int) {
	return file_sysmanager_proto_rawDescGZIP(), []int{3}
}

func (x *EnclosureControlResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// ================================================
// EXAMPLE 02: SERVER STREAMING MESSAGES (Telemetry)
// ================================================
type WeatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrequencyMs   int32                  `protobuf:"varint,1,opt,name=frequency_ms,json=frequencyMs,proto3" json:"frequency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherRequest) Reset() {
	*x = WeatherRequest{}
	mi := &file_sysmanager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherRequest) ProtoMessage() {}

func (x *WeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sysmanager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherRequest.ProtoReflect.Descriptor instead.
func (*WeatherRequest) Descriptor() ([]byte, []int) {
	return file_sysmanager_proto_rawDescGZIP(), []int{4}
}

func (x *WeatherRequest) GetFrequencyMs() int32 {
	if x != nil {
		return x.FrequencyMs
	}
	return 0
}

type WeatherTelemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindSpeed     float32                `protobuf:"fixed32,1,opt,name=wind_speed,json=windSpeed,proto3" json:"wind_speed,omitempty"`
	Temperature   float32                `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherTelemetry) Reset() {
	*x = WeatherTelemetry{}
	mi := &file_sysmanager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherTelemetry) ProtoMessage() {}

func (x *WeatherTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_sysmanager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherTelemetry.ProtoReflect.Descriptor instead.
func (*WeatherTelemetry) Descriptor() ([]byte, []int) {
	return file_sysmanager_proto_rawDescGZIP(), []int{5}
}

func (x *WeatherTelemetry) GetWindSpeed() float32 {
	if x != nil {
		return x.WindSpeed
	}
	return 0
}

func (x *WeatherTelemetry) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

// ================================================
// EXAMPLE 03: CLIENT STREAMING MESSAGES (Firmware Upload)
// ================================================
type FirmwareChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkIndex    int32                  `protobuf:"varint,1,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	DataPayload   string                 `protobuf:"bytes,2,opt,name=data_payload,json=dataPayload,proto3" json:"data_payload,omitempty"` // Simulated byte Array
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmwareChunk) Reset() {
	*x = FirmwareChunk{}
	mi := &file_sysmanager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareChunk) ProtoMessage() {}

func (x *FirmwareChunk) ProtoReflect() protoreflect.Message {
	mi := &file_sysmanager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareChunk.ProtoReflect.Descriptor instead.
func (*FirmwareChunk) Descriptor() ([]byte, []int) {
	return file_sysmanager_proto_rawDescGZIP(), []int{6}
}

func (x *FirmwareChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *FirmwareChunk) GetDataPayload() string {
	if x != nil {
		return x.DataPayload
	}
	return ""
}

type UploadResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalBytesReceived int32                  `protobuf:"varint,1,opt,name=total_bytes_received,json=totalBytesReceived,proto3" json:"total_bytes_received,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UploadResult) Reset() {
	*x = UploadResult{}
	mi := &file_sysmanager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResult) ProtoMessage() {}

func (x *UploadResult) ProtoReflect() protoreflect.Message {
	mi := &file_sysmanager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResult.ProtoReflect.Descriptor instead.
func (*UploadResult) Descriptor() ([]byte, []int) {
	return file_sysmanager_proto_rawDescGZIP(), []int{7}
}

func (x *UploadResult) GetTotalBytesReceived() int32 {
	if x != nil {
		return x.TotalBytesReceived
	}
	return 0
}

// ================================================
// EXAMPLE 04: BIDIRECTIONAL STREAMING MESSAGES (Control Loop)
// ================================================
type MotorCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetPosition float32                `protobuf:"fixed32,1,opt,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MotorCommand) Reset() {
	*x = MotorCommand{}
	mi := &file_sysmanager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MotorCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotorCommand) ProtoMessage() {}

func (x *MotorCommand) ProtoReflect() protoreflect.Message {
	mi := &file_sysmanager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotorCommand.ProtoReflect.Descriptor instead.
func (*MotorCommand) Descriptor() ([]byte, []int) {
	return file_sysmanager_proto_rawDescGZIP(), []int{8}
}

func (x *MotorCommand) GetTargetPosition() float32 {
	if x != nil {
		return x.TargetPosition
	}
	return 0
}

type MotorTelemetry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentPosition float32                `protobuf:"fixed32,1,opt,name=current_position,json=currentPosition,proto3" json:"current_position,omitempty"`
	IsMoving        bool                   `protobuf:"varint,2,opt,name=is_moving,json=isMoving,proto3" json:"is_moving,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MotorTelemetry) Reset() {
	*x = MotorTelemetry{}
	mi := &file_sysmanager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MotorTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotorTelemetry) ProtoMessage() {}

func (x *MotorTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_sysmanager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotorTelemetry.ProtoReflect.Descriptor instead.
func (*MotorTelemetry) Descriptor() ([]byte, []int) {
	return file_sysmanager_proto_rawDescGZIP(), []int{9}
}

func (x *MotorTelemetry) GetCurrentPosition() float32 {
	if x != nil {
		return x.CurrentPosition
	}
	return 0
}

func (x *MotorTelemetry) GetIsMoving() bool {
	if x != nil {
		return x.IsMoving
	}
	return false
}

var File_sysmanager_proto protoreflect.FileDescriptor

const file_sysmanager_proto_rawDesc = "" +
	"\n" +
	"\x10sysmanager.proto\x12\n" +
	"sysmanager\"6\n" +
	"\rStatusRequest\x12%\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tR\rcomponentName\"R\n" +
	"\x0eStatusResponse\x12\x1b\n" +
	"\tis_online\x18\x01 \x01(\bR\bisOnline\x12#\n" +
	"\rcurrent_state\x18\x02 \x01(\tR\fcurrentState\"1\n" +
	"\x17EnclosureControlRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\x05R\x06action\"2\n" +
	"\x18EnclosureControlResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"3\n" +
	"\x0eWeatherRequest\x12!\n" +
	"\ffrequency_ms\x18\x01 \x01(\x05R\vfrequencyMs\"S\n" +
	"\x10WeatherTelemetry\x12\x1d\n" +
	"\n" +
	"wind_speed\x18\x01 \x01(\x02R\twindSpeed\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x02R\vtemperature\"S\n" +
	"\rFirmwareChunk\x12\x1f\n" +
	"\vchunk_index\x18\x01 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\fdata_payload\x18\x02 \x01(\tR\vdataPayload\"@\n" +
	"\fUploadResult\x120\n" +
	"\x14total_bytes_received\x18\x01 \x01(\x05R\x12totalBytesReceived\"7\n" +
	"\fMotorCommand\x12'\n" +
	"\x0ftarget_position\x18\x01 \x01(\x02R\x0etargetPosition\"X\n" +
	"\x0eMotorTelemetry\x12)\n" +
	"\x10current_position\x18\x01 \x01(\x02R\x0fcurrentPosition\x12\x1b\n" +
	"\tis_moving\x18\x02 \x01(\bR\bisMoving*\x8d\x01\n" +
	"\vSystemState\x12\x1c\n" +
	"\x18SYSTEM_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SYSTEM_STATE_BOOTING\x10\x01\x12\x15\n" +
	"\x11SYSTEM_STATE_IDLE\x10\x02\x12\x17\n" +
	"\x13SYSTEM_STATE_ACTIVE\x10\x03\x12\x16\n" +
	"\x12SYSTEM_STATE_FAULT\x10\x042\xae\x03\n" +
	"\rSystemManager\x12H\n" +
	"\x0fGetSystemStatus\x12\x19.sysmanager.StatusRequest\x1a\x1a.sysmanager.StatusResponse\x12d\n" +
	"\x17TriggerEnclosureControl\x12#.sysmanager.EnclosureControlRequest\x1a$.sysmanager.EnclosureControlResponse\x12T\n" +
	"\x16StreamWeatherTelemetry\x12\x1a.sysmanager.WeatherRequest\x1a\x1c.sysmanager.WeatherTelemetry0\x01\x12G\n" +
	"\x0eUploadFirmware\x12\x19.sysmanager.FirmwareChunk\x1a\x18.sysmanager.UploadResult(\x01\x12N\n" +
	"\x12ActiveMotorControl\x12\x18.sysmanager.MotorCommand\x1a\x1a.sysmanager.MotorTelemetry(\x010\x01B\x0eZ\f./sysmanagerb\x06proto3"

var (
	file_sysmanager_proto_rawDescOnce sync.Once
	file_sysmanager_proto_rawDescData []byte
)

func file_sysmanager_proto_rawDescGZIP() []byte {
	file_sysmanager_proto_rawDescOnce.Do(func() {
		file_sysmanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sysmanager_proto_rawDesc), len(file_sysmanager_proto_rawDesc)))
	})
	return file_sysmanager_proto_rawDescData
}

var file_sysmanager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sysmanager_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sysmanager_proto_goTypes = []any{
	(SystemState)(0),                 // 0: sysmanager.SystemState
	(*StatusRequest)(nil),            // 1: sysmanager.StatusRequest
	(*StatusResponse)(nil),           // 2: sysmanager.StatusResponse
	(*EnclosureControlRequest)(nil),  // 3: sysmanager.EnclosureControlRequest
	(*EnclosureControlResponse)(nil), // 4: sysmanager.EnclosureControlResponse
	(*WeatherRequest)(nil),           // 5: sysmanager.WeatherRequest
	(*WeatherTelemetry)(nil),         // 6: sysmanager.WeatherTelemetry
	(*FirmwareChunk)(nil),            // 7: sysmanager.FirmwareChunk
	(*UploadResult)(nil),             // 8: sysmanager.UploadResult
	(*MotorCommand)(nil),             // 9: sysmanager.MotorCommand
	(*MotorTelemetry)(nil),           // 10: sysmanager.MotorTelemetry
}
var file_sysmanager_proto_depIdxs = []int32{
	1,  // 0: sysmanager.SystemManager.GetSystemStatus:input_type -> sysmanager.StatusRequest
	3,  // 1: sysmanager.SystemManager.TriggerEnclosureControl:input_type -> sysmanager.EnclosureControlRequest
	5,  // 2: sysmanager.SystemManager.StreamWeatherTelemetry:input_type -> sysmanager.WeatherRequest
	7,  // 3: sysmanager.SystemManager.UploadFirmware:input_type -> sysmanager.FirmwareChunk
	9,  // 4: sysmanager.SystemManager.ActiveMotorControl:input_type -> sysmanager.MotorCommand
	2,  // 5: sysmanager.SystemManager.GetSystemStatus:output_type -> sysmanager.StatusResponse
	4,  // 6: sysmanager.SystemManager.TriggerEnclosureControl:output_type -> sysmanager.EnclosureControlResponse
	6,  // 7: sysmanager.SystemManager.StreamWeatherTelemetry:output_type -> sysmanager.WeatherTelemetry
	8,  // 8: sysmanager.SystemManager.UploadFirmware:output_type -> sysmanager.UploadResult
	10, // 9: sysmanager.SystemManager.ActiveMotorControl:output_type -> sysmanager.MotorTelemetry
	5,  // [5:10] is the sub-list for method output_type
	0,  // [0:5] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_sysmanager_proto_init() }
func file_sysmanager_proto_init() {
	if File_sysmanager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sysmanager_proto_rawDesc), len(file_sysmanager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sysmanager_proto_goTypes,
		DependencyIndexes: file_sysmanager_proto_depIdxs,
		EnumInfos:         file_sysmanager_proto_enumTypes,
		MessageInfos:      file_sysmanager_proto_msgTypes,
	}.Build()
	File_sysmanager_proto = out.File
	file_sysmanager_proto_goTypes = nil
	file_sysmanager_proto_depIdxs = nil
}
